
exports.HttpStatusCode = {
    STATUS_OK: 200,
    STATUS_CREATED: 201,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_FORBIDDEN: 403,
    STATUS_RESOURCE_NOT_FOUND: 404,
    STATUS_UNPROCESSABLE_ENTITY: 422,
    STATUS_INTERNAL_SERVER_ERROR: 500,
  };
  
  exports.ResponseStatus = {
    SUCCESS: 'success',
    FAILURE: 'error',
  };